import JSZip from 'jszip';
import type { ExportPayload, ArbitrageConfig } from '@/types/bot';

// ── Validation ──
const ALLOWED_PAIRS = ['SOL/USDC', 'ETH/USDC', 'BTC/USDC'];
const ALLOWED_EXCHANGES = ['jupiter', 'raydium', 'orca'];
const ALLOWED_SPEEDS = ['standard', 'jito'] as const;

function validatePayload(body: unknown): ExportPayload {
  if (!body || typeof body !== 'object') throw new Error('Invalid payload');
  const obj = body as Record<string, unknown>;
  const config = obj.config;
  if (!config || typeof config !== 'object') throw new Error('Invalid config');
  const cfg = config as Record<string, unknown>;

  if (!ALLOWED_PAIRS.includes(cfg.tradingPair as string)) throw new Error('Invalid tradingPair');
  if (!Array.isArray(cfg.exchanges) || !cfg.exchanges.every((e: unknown) => ALLOWED_EXCHANGES.includes(e as string))) throw new Error('Invalid exchanges');
  const minProfit = Number(cfg.minProfitUsdc);
  if (!Number.isFinite(minProfit) || minProfit < 0.5 || minProfit > 10000) throw new Error('Invalid minProfitUsdc');
  const maxSize = Number(cfg.maxTradeSizeSol);
  if (!Number.isFinite(maxSize) || maxSize < 0.1 || maxSize > 100) throw new Error('Invalid maxTradeSizeSol');
  if (!ALLOWED_SPEEDS.includes(cfg.executionSpeed as typeof ALLOWED_SPEEDS[number])) throw new Error('Invalid executionSpeed');
  const tip = Number(cfg.jitoTipSol);
  if (!Number.isFinite(tip) || tip < 0 || tip > 10) throw new Error('Invalid jitoTipSol');
  return { config: { tradingPair: cfg.tradingPair as string, exchanges: cfg.exchanges as string[], minProfitUsdc: minProfit, maxTradeSizeSol: maxSize, executionSpeed: cfg.executionSpeed as ArbitrageConfig['executionSpeed'], jitoTipSol: tip } };
}

// ── Mint addresses ──
const MINT: Record<string, string> = {
  SOL: 'So11111111111111111111111111111111111111112',
  USDC: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
  ETH: '7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs',
  BTC: '3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh',
};

// ── Template generators ──

function genPackageJson(p: ExportPayload): string {
  const deps: Record<string, string> = { 
    '@solana/web3.js': '^1.95.3', 
    '@solana/spl-token': '^0.4.8',
    'dotenv': '^16.4.5', 
    'bs58': '^6.0.0',
    '@jup-ag/api': '^6.0.29'
  };
  const arb = p.config as ArbitrageConfig;
  if (arb.executionSpeed === 'jito') deps['jito-ts'] = '^4.1.1';
  return JSON.stringify({ name: 'arbitrator-bot', version: '1.0.0', description: 'Solana cross-DEX arbitrage bot — generated by Arbitrator', main: 'dist/index.js', scripts: { build: 'tsc', start: 'ts-node src/index.ts' }, dependencies: deps, devDependencies: { 'ts-node': '^10.9.2', typescript: '^5.4.5', '@types/node': '^20.14.0' } }, null, 2) + '\n';
}

const TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2022", "module": "commonjs", "lib": ["ES2022"],
    "outDir": "./dist", "rootDir": "./src", "strict": true,
    "esModuleInterop": true, "skipLibCheck": true, "resolveJsonModule": true,
    "forceConsistentCasingInFileNames": true, "declaration": true
  },
  "include": ["src/**/*"]
}
`;

const ENV_EXAMPLE = `# ─── RPC Connection ───
SOLANA_RPC_URL=https://mainnet.helius-rpc.com/?api-key=YOUR_KEY_HERE
SOLANA_WSS_URL=wss://mainnet.helius-rpc.com/?api-key=YOUR_KEY_HERE

# ─── Private Key (JSON byte array or base58) ───
USER_PRIVATE_KEY=[12,34,56,...your_private_key...]

# ─── Jupiter API Key (free at https://portal.jup.ag) ───
JUPITER_API_KEY=

# ─── Jito (optional) ───
JITO_BLOCK_ENGINE_URL=https://mainnet.block-engine.jito.wtf
`;

const UTILS_TS = `import { LAMPORTS_PER_SOL } from '@solana/web3.js';

export function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

export async function retryWithBackoff<T>(
  fn: () => Promise<T>,
  maxRetries: number = 3,
  baseDelay: number = 1000
): Promise<T> {
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      return await fn();
    } catch (err) {
      if (attempt === maxRetries) throw err;
      const delay = baseDelay * Math.pow(2, attempt) + Math.random() * 500;
      log('RETRY', \`Attempt \${attempt + 1} failed, retrying in \${Math.round(delay)}ms...\`);
      await sleep(delay);
    }
  }
  throw new Error('Unreachable');
}

export function formatSol(lamports: number): string {
  return (lamports / LAMPORTS_PER_SOL).toFixed(6) + ' SOL';
}

export function formatUsdc(microUsdc: number): string {
  return '$' + (microUsdc / 1e6).toFixed(2);
}

export function log(tag: string, message: string): void {
  const ts = new Date().toISOString().slice(11, 23);
  console.log(\`[\${ts}] [\${tag}] \${message}\`);
}
`;

function genConfigTs(p: ExportPayload): string {
  const arb = p.config as ArbitrageConfig;
  const [inputToken] = arb.tradingPair.split('/');
  return `import { Connection, Keypair, LAMPORTS_PER_SOL } from '@solana/web3.js';
import bs58 from 'bs58';
import dotenv from 'dotenv';
dotenv.config();

// ─── Token Mints ───
export const INPUT_MINT = '${MINT[inputToken] || MINT.SOL}';  // ${inputToken}
export const OUTPUT_MINT = '${MINT.USDC}'; // USDC

// ─── Strategy Settings ───
export const BOT = {
  TYPE: 'arbitrage' as const,
  TRADE_AMOUNT_LAMPORTS: Math.floor(${arb.maxTradeSizeSol} * LAMPORTS_PER_SOL),
  TRADE_AMOUNT_SOL: ${arb.maxTradeSizeSol},
  MIN_PROFIT_USDC: ${arb.minProfitUsdc},
  SLIPPAGE_BPS: 10,
  USE_JITO: ${arb.executionSpeed === 'jito'},
  JITO_TIP_LAMPORTS: Math.floor(${arb.jitoTipSol} * LAMPORTS_PER_SOL),
  POLL_INTERVAL_MS: 3000,
  JUPITER_API: 'https://api.jup.ag/swap/v1',
  JUPITER_API_KEY: process.env.JUPITER_API_KEY || '',
};

// ─── Execution Limits ───
export const LIMITS = {
  MAX_CU: 400_000,
  MAX_RETRIES: 3,
  BLOCKHASH_RETRY_DELAY_MS: 500,
  TX_SIZE_LIMIT: 1232,
  WS_RECONNECT_BASE_MS: 1000,
  WS_RECONNECT_MAX_MS: 30_000,
  RPC_RATE_LIMIT_MS: 200,
};

// ─── Connection ───
export const connection = new Connection(process.env.SOLANA_RPC_URL || '', {
  commitment: 'confirmed',
  wsEndpoint: process.env.SOLANA_WSS_URL || undefined,
  confirmTransactionInitialTimeout: 30_000,
});

// ─── Wallet ───
export function loadWallet(): Keypair {
  const key = process.env.USER_PRIVATE_KEY || '';
  if (!key) throw new Error('Set USER_PRIVATE_KEY in .env');
  try { return Keypair.fromSecretKey(Uint8Array.from(JSON.parse(key))); }
  catch { return Keypair.fromSecretKey(bs58.decode(key)); }
}
`;
}

function genMonitorTs(p: ExportPayload): string {
  const arb = p.config as ArbitrageConfig;
  const [inputToken] = arb.tradingPair.split('/');
  return `import { connection, BOT, LIMITS, INPUT_MINT, OUTPUT_MINT } from './config';
import { log, sleep, retryWithBackoff } from './utils';

export interface ArbOpportunity {
  buyQuote: any;
  sellQuote: any;
  profitUsdc: number;
  priceImpact: number;
}

// ─── Rate-limited Jupiter quote fetcher ───
let lastRpcCall = 0;

async function rateLimitedFetch(url: string): Promise<any> {
  const now = Date.now();
  const wait = LIMITS.RPC_RATE_LIMIT_MS - (now - lastRpcCall);
  if (wait > 0) await sleep(wait);
  lastRpcCall = Date.now();

  return retryWithBackoff(async () => {
    const headers: Record<string, string> = { 'Accept': 'application/json' };
    if (BOT.JUPITER_API_KEY) headers['x-api-key'] = BOT.JUPITER_API_KEY;
    const res = await fetch(url, {
      headers,
      signal: AbortSignal.timeout(8000),
    });
    if (res.status === 429) {
      log('MONITOR', 'Rate limited by Jupiter API, backing off...');
      throw new Error('Rate limited');
    }
    if (!res.ok) throw new Error(\`Jupiter API \${res.status}\`);
    return res.json();
  }, 3, 1000);
}

// NOTE: We request quotes that DO NOT natively wrap/unwrap SOL. We manage WSOL ourselves.
async function getQuote(inputMint: string, outputMint: string, amount: number): Promise<any> {
  const url = \`\${BOT.JUPITER_API}/quote?inputMint=\${inputMint}&outputMint=\${outputMint}&amount=\${amount}&slippageBps=\${BOT.SLIPPAGE_BPS}&onlyDirectRoutes=false\`;
  return rateLimitedFetch(url);
}

let wsSubscriptionId: number | null = null;
let reconnectAttempt = 0;
let isShuttingDown = false;

function setupWsReconnection() {
  try {
    const ws = (connection as any)._rpcWebSocket;
    if (!ws) return;
    ws.on('close', () => {
      if (isShuttingDown) return;
      const delay = Math.min(
        LIMITS.WS_RECONNECT_BASE_MS * Math.pow(2, reconnectAttempt),
        LIMITS.WS_RECONNECT_MAX_MS
      );
      reconnectAttempt++;
      log('WS', \`Connection dropped. Reconnecting in \${delay}ms (attempt \${reconnectAttempt})...\`);
      setTimeout(() => {
        if (!isShuttingDown) {
          reconnectAttempt = 0;
          log('WS', 'Reconnected successfully.');
        }
      }, delay);
    });
    ws.on('error', (err: Error) => log('WS', \`Error: \${err.message}\`));
  } catch {
    log('WS', 'WebSocket event binding skipped (not available).');
  }
}

export async function startMonitor(onOpportunity: (data: ArbOpportunity) => void): Promise<() => void> {
  log('MONITOR', 'Starting Arbitrator monitor...');
  log('MONITOR', \`Pair: ${arb.tradingPair} | Size: \${BOT.TRADE_AMOUNT_SOL} SOL | Poll: \${BOT.POLL_INTERVAL_MS}ms\`);

  setupWsReconnection();

  const poll = async () => {
    try {
      // Leg 1: ${inputToken} → USDC
      const buyQuote = await getQuote(INPUT_MINT, OUTPUT_MINT, BOT.TRADE_AMOUNT_LAMPORTS);
      if (!buyQuote || !buyQuote.outAmount) throw new Error('Leg 1 quote failed');
      const usdcReceived = Number(buyQuote.outAmount) / 1e6;
      const impactBuy = Math.abs(Number(buyQuote.priceImpactPct || 0));

      // Leg 2: USDC → ${inputToken} (round-trip)
      const sellQuote = await getQuote(OUTPUT_MINT, INPUT_MINT, Number(buyQuote.outAmount));
      if (!sellQuote || !sellQuote.outAmount) throw new Error('Leg 2 quote failed');
      const solBack = Number(sellQuote.outAmount) / 1e9;
      const impactSell = Math.abs(Number(sellQuote.priceImpactPct || 0));

      // Profit calc
      const profitSol = solBack - BOT.TRADE_AMOUNT_SOL;
      const pricePerSol = usdcReceived / BOT.TRADE_AMOUNT_SOL;
      const profitUsdc = profitSol * pricePerSol;
      const totalImpact = impactBuy + impactSell;

      log('MONITOR', \`\${BOT.TRADE_AMOUNT_SOL} SOL → $\${usdcReceived.toFixed(2)} → \${solBack.toFixed(6)} SOL | Profit: $\${profitUsdc.toFixed(4)} | Impact: \${totalImpact.toFixed(4)}%\`);

      if (profitUsdc >= BOT.MIN_PROFIT_USDC) {
        onOpportunity({ buyQuote, sellQuote, profitUsdc, priceImpact: totalImpact });
      }
    } catch (err) {
      log('MONITOR', \`Error: \${(err as Error).message}\`);
    }
  };

  await poll();
  const intervalId = setInterval(poll, BOT.POLL_INTERVAL_MS);

  return () => {
    isShuttingDown = true;
    clearInterval(intervalId);
    if (wsSubscriptionId !== null) connection.removeAccountChangeListener(wsSubscriptionId).catch(() => {});
    log('MONITOR', 'Stopped.');
  };
}
`;
}

function genMathTs(p: ExportPayload): string {
  return `import { BOT, LIMITS } from './config';
import { log } from './utils';

interface ArbOpportunity { buyQuote: any; sellQuote: any; profitUsdc: number; priceImpact: number; }

export interface ProfitBreakdown {
  profitable: boolean;
  grossProfitUsdc: number;
  jitoTipUsdc: number;
  cuCostUsdc: number;
  netProfitUsdc: number;
}

export function evaluateOpportunity(opp: ArbOpportunity): ProfitBreakdown {
  // Profit in USDC
  const grossProfitUsdc = opp.profitUsdc;

  // Jito tip
  const solPrice = (Number(opp.buyQuote.outAmount) / 1e6) / BOT.TRADE_AMOUNT_SOL;
  const jitoTipUsdc = BOT.USE_JITO ? (BOT.JITO_TIP_LAMPORTS / 1e9) * solPrice : 0;

  // Transaction base fee + conservative dynamic priority fee estimation
  const txFeeSol = 0.00001;
  const cuCostUsdc = txFeeSol * solPrice;

  const netProfitUsdc = grossProfitUsdc - jitoTipUsdc - cuCostUsdc;
  const profitable = netProfitUsdc >= BOT.MIN_PROFIT_USDC;

  log('MATH', [
    \`Gross: $\${grossProfitUsdc.toFixed(4)}\`,
    \`Gas: -$\${cuCostUsdc.toFixed(4)}\`,
    \`Tip: -$\${jitoTipUsdc.toFixed(4)}\`,
    \`Net: $\${netProfitUsdc.toFixed(4)}\`,
    profitable ? 'PROFITABLE' : 'SKIP',
  ].join(' | '));

  return { profitable, grossProfitUsdc, cuCostUsdc, jitoTipUsdc, netProfitUsdc };
}
`;
}

function genExecutorTs(p: ExportPayload): string {
  const arb = p.config as ArbitrageConfig;
  const useJito = arb.executionSpeed === 'jito';
  return `import {
  VersionedTransaction, TransactionMessage, ComputeBudgetProgram,
  SystemProgram, PublicKey, AddressLookupTableAccount,
  TransactionInstruction,
} from '@solana/web3.js';
import { 
  createSyncNativeInstruction, 
  createAssociatedTokenAccountIdempotentInstruction, 
  createCloseAccountInstruction, 
  getAssociatedTokenAddressSync,
  NATIVE_MINT
} from '@solana/spl-token';
import { connection, BOT, LIMITS, loadWallet } from './config';
import { log, retryWithBackoff } from './utils';

interface ArbOpportunity { buyQuote: any; sellQuote: any; profitUsdc: number; priceImpact: number; }

function deserializeIx(ix: any): TransactionInstruction {
  return new TransactionInstruction({
    programId: new PublicKey(ix.programId),
    keys: ix.accounts.map((a: any) => ({ pubkey: new PublicKey(a.pubkey), isSigner: a.isSigner, isWritable: a.isWritable })),
    data: Buffer.from(ix.data, 'base64'),
  });
}

async function getDynamicPriorityFee(accounts: PublicKey[]): Promise<number> {
  try {
    const fees = await connection.getRecentPrioritizationFees({ lockedWritableAccounts: accounts.slice(0, 5) });
    if (!fees.length) return 50_000;
    const sorted = fees.map(f => f.prioritizationFee).sort((a, b) => a - b);
    const median = sorted[Math.floor(sorted.length / 2)];
    return Math.max(median, 1_000);
  } catch { return 50_000; }
}

function validateTxSize(tx: VersionedTransaction): boolean {
  const size = tx.serialize().length;
  if (size > LIMITS.TX_SIZE_LIMIT) {
    log('EXEC', \`TX too large: \${size} bytes\`);
    return false;
  }
  return true;
}

export async function executeTrade(opportunity: ArbOpportunity): Promise<void> {
  const wallet = loadWallet();
  const owner = wallet.publicKey;
  log('EXEC', \`Wallet: \${owner.toBase58().slice(0, 8)}... | Target Profit: $\${opportunity.profitUsdc.toFixed(4)}\`);

  // ─── Jupiter Swap Configuration ───
  // We explicitly tell Jupiter NOT to wrap/unwrap SOL automatically.
  // Why? Because we are stitching two separate swaps (Leg 1 & Leg 2) together into a single atomic transaction.
  // If Jupiter wrapped and unwrapped SOL for each leg, the WSOL account wouldn't persist between them.
  // Instead, we manage the WSOL lifecycle manually across the entire transaction.
  const swapConfig = {
    userPublicKey: owner.toBase58(),
    wrapAndUnwrapSol: false,
    dynamicComputeUnitLimit: true,
    prioritizationFeeLamports: 'auto',
  };

  const jupHeaders: Record<string, string> = { 'Content-Type': 'application/json' };
  if (BOT.JUPITER_API_KEY) jupHeaders['x-api-key'] = BOT.JUPITER_API_KEY;

  // 1. Fetch exact transaction instructions for Leg 1 (Input Token -> USDC)
  const buyRes = await fetch(\`\${BOT.JUPITER_API}/swap-instructions\`, {
    method: 'POST', headers: jupHeaders,
    body: JSON.stringify({ quoteResponse: opportunity.buyQuote, ...swapConfig }),
  });
  if (!buyRes.ok) throw new Error(\`Leg 1 Swap instructions failed: \${buyRes.status}\`);
  const buySwap = await buyRes.json();
  if (buySwap.error) throw new Error(\`Jupiter Leg 1: \${buySwap.error}\`);

  // 2. Fetch exact transaction instructions for Leg 2 (USDC -> Input Token)
  const sellRes = await fetch(\`\${BOT.JUPITER_API}/swap-instructions\`, {
    method: 'POST', headers: jupHeaders,
    body: JSON.stringify({ quoteResponse: opportunity.sellQuote, ...swapConfig }),
  });
  if (!sellRes.ok) throw new Error(\`Leg 2 Swap instructions failed: \${sellRes.status}\`);
  const sellSwap = await sellRes.json();
  if (sellSwap.error) throw new Error(\`Jupiter Leg 2: \${sellSwap.error}\`);

  // ─── Address Lookup Table (ALT) Deduplication ───
  // Solana transactions have a strict 1232 byte size limit.
  // Since we are combining two complex swaps, the transaction can easily exceed this limit.
  // We extract ALTs from both swap legs, deduplicate them, and fetch the table accounts.
  const lookupTablesMap = new Map<string, AddressLookupTableAccount>();
  const allAlts = [...(buySwap.addressLookupTableAddresses || []), ...(sellSwap.addressLookupTableAddresses || [])];
  
  for (const addr of allAlts) {
    if (!lookupTablesMap.has(addr)) {
      const result = await connection.getAddressLookupTable(new PublicKey(addr));
      if (result.value) lookupTablesMap.set(addr, result.value);
    }
  }
  const lookupTables = Array.from(lookupTablesMap.values());

  // ─── Manual WSOL Lifecycle Management ───
  // To trade SOL natively through smart contracts, it must be Wrapped SOL (WSOL).
  const wsolAta = getAssociatedTokenAddressSync(NATIVE_MINT, owner);
  
  const ixs: TransactionInstruction[] = [];

  // Step A: Create the WSOL token account (if it doesn't exist) and fund it with our trade amount

  ixs.push(createAssociatedTokenAccountIdempotentInstruction(owner, wsolAta, owner, NATIVE_MINT));
  ixs.push(SystemProgram.transfer({ fromPubkey: owner, toPubkey: wsolAta, lamports: BOT.TRADE_AMOUNT_LAMPORTS }));
  ixs.push(createSyncNativeInstruction(wsolAta));

  // Leg 1 (WSOL -> USDC)
  if (buySwap.setupInstructions) ixs.push(...buySwap.setupInstructions.map(deserializeIx));
  ixs.push(deserializeIx(buySwap.swapInstruction));
  if (buySwap.cleanupInstruction) ixs.push(deserializeIx(buySwap.cleanupInstruction)); // e.g., closing temporary non-WSOL ATAs

  // Leg 2 (USDC -> WSOL)
  if (sellSwap.setupInstructions) ixs.push(...sellSwap.setupInstructions.map(deserializeIx));
  ixs.push(deserializeIx(sellSwap.swapInstruction));
  if (sellSwap.cleanupInstruction) ixs.push(deserializeIx(sellSwap.cleanupInstruction));

  // Teardown WSOL account (unwraps all WSOL back to SOL)
  ixs.push(createCloseAccountInstruction(wsolAta, owner, owner));

  ${useJito ? `// ─── Jito Bundle ───
  const JITO_TIPS = [
    '96gYZGLnJYVFmbjzopPSU6QiEV5fGqZNyN9nmNhvrZU5',
    'HFqU5x63VTqvQss8hp11i4bVqkfRtk6rz6jZUem2wFF8',
    'Cw8CFyM9FkoMi7K7Crf6HNQqf4uEMzpKw6QNghXLvLkY',
    'ADaUMid9yfUytqMBgopwjb2DTLSLBVCzM0VKL1aYnKbn',
    'DfXygSm4jCyNCybVYYK6DwvWqjKee8pbDmJGcLWNDXjh',
  ];
  const tipAccount = new PublicKey(JITO_TIPS[Math.floor(Math.random() * JITO_TIPS.length)]);
  ixs.push(SystemProgram.transfer({ fromPubkey: owner, toPubkey: tipAccount, lamports: BOT.JITO_TIP_LAMPORTS }));
  
  // Set generous compute unit limit since Jito charges via tip
  ixs.unshift(ComputeBudgetProgram.setComputeUnitLimit({ units: LIMITS.MAX_CU }));
  ` : `// ─── Standard Priority Fees ───
  const writableAccounts = ixs.flatMap(ix => ix.keys.filter(k => k.isWritable).map(k => k.pubkey));
  const priorityFee = await getDynamicPriorityFee(writableAccounts);
  ixs.unshift(
    ComputeBudgetProgram.setComputeUnitLimit({ units: LIMITS.MAX_CU }),
    ComputeBudgetProgram.setComputeUnitPrice({ microLamports: priorityFee })
  );`}

  // ─── Build, validate size, send with retry ───
  await retryWithBackoff(async () => {
    const { blockhash, lastValidBlockHeight } = await connection.getLatestBlockhash('confirmed');
    const msg = new TransactionMessage({
      payerKey: owner, recentBlockhash: blockhash, instructions: ixs,
    }).compileToV0Message(lookupTables);
    const tx = new VersionedTransaction(msg);
    tx.sign([wallet]);

    if (!validateTxSize(tx)) throw new Error('Transaction exceeds 1232 byte limit');

    ${useJito ? `const jitoUrl = process.env.JITO_BLOCK_ENGINE_URL || 'https://mainnet.block-engine.jito.wtf';
    log('EXEC', \`Sending Jito bundle to \${jitoUrl}...\`);
    const bundleRes = await fetch(\`\${jitoUrl}/api/v1/bundles\`, {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'sendBundle', params: [[Buffer.from(tx.serialize()).toString('base64')]] }),
    });
    const result = await bundleRes.json();
    log('EXEC', \`Jito result: \${JSON.stringify(result)}\`);` : `log('EXEC', 'Sending via standard RPC...');
    const sig = await connection.sendRawTransaction(tx.serialize(), { skipPreflight: false, maxRetries: 3 });
    log('EXEC', \`Sent: \${sig}\`);

    const confirm = await connection.confirmTransaction({ signature: sig, blockhash, lastValidBlockHeight }, 'confirmed');
    if (confirm.value.err) throw new Error(\`TX failed: \${JSON.stringify(confirm.value.err)}\`);
    log('EXEC', 'Confirmed!');`}
  }, LIMITS.MAX_RETRIES, LIMITS.BLOCKHASH_RETRY_DELAY_MS);
}
`;
}

function genIndexTs(p: ExportPayload): string {
  return `import { startMonitor } from './monitor';
import { evaluateOpportunity } from './math';
import { executeTrade } from './executor';
import { BOT, connection, loadWallet } from './config';
import { log } from './utils';

let cleanupMonitor: (() => void) | null = null;
let stats = { scanned: 0, opportunities: 0, executed: 0, errors: 0 };

async function main() {
  log('SYS', 'Booting Arbitrator Engine...');
  try {
    const wallet = loadWallet();
    log('SYS', \`Loaded wallet: \${wallet.publicKey.toBase58()}\`);
  } catch (err) {
    log('SYS', \`FATAL: \${(err as Error).message}\`);
    process.exit(1);
  }
  
  cleanupMonitor = await startMonitor(async (opp) => {
    stats.opportunities++;
    const { profitable } = evaluateOpportunity(opp);
    if (!profitable) return;

    try {
      await executeTrade(opp);
      stats.executed++;
    } catch (err) {
      stats.errors++;
      log('ERR', \`Execution failed: \${(err as Error).message}\`);
    }
  });

  process.on('SIGINT', shutdown);
  process.on('SIGTERM', shutdown);
}

function shutdown() {
  log('SYS', 'Graceful shutdown initiated...');
  if (cleanupMonitor) cleanupMonitor();
  log('SYS', \`Session Stats - Opps: \${stats.opportunities} | Exec: \${stats.executed} | Errors: \${stats.errors}\`);
  process.exit(0);
}

main().catch((err) => {
  log('SYS', \`Fatal Error: \${err.message}\`);
  process.exit(1);
});
`;
}

const README_MD = [
  '# Arbitrator Bot',
  '',
  'A self-custodial cross-DEX spatial arbitrage bot for Solana.',
  '',
  '---',
  '',
  '## What This Bot Does',
  '',
  'This bot monitors price differences between decentralized exchanges on Solana',
  '(via Jupiter aggregated routing) and executes round-trip trades when the',
  'spread exceeds your configured profit threshold.',
  '',
  'It buys a token on one route and sells it back on another in a single atomic',
  'transaction. If the round-trip returns more than you started with (after fees),',
  'that difference is your profit.',
  '',
  '## Prerequisites',
  '',
  '- Node.js 18 or later',
  '- A Solana wallet with SOL for trading capital and fees',
  '- A Solana RPC endpoint (Helius, QuickNode, or similar)',
  '- A Jupiter API key (optional but recommended)',
  '',
  '## Setup',
  '',
  '### 1. Install dependencies',
  '',
  '```bash',
  'npm install',
  '```',
  '',
  '### 2. Configure environment variables',
  '',
  'Copy the example file and fill in your values:',
  '',
  '```bash',
  'cp .env.example .env',
  '```',
  '',
  '### 3. Get a Solana RPC URL',
  '',
  'You need an RPC endpoint with WebSocket support. Free options:',
  '',
  '- **Helius**: Sign up at https://helius.dev, create a project, copy the mainnet',
  '  RPC URL. The WebSocket URL uses wss:// instead of https://.',
  '- **QuickNode**: Sign up at https://quicknode.com, create a Solana mainnet endpoint.',
  '',
  '### 4. Get a Jupiter API key (recommended)',
  '',
  'Without an API key, you are limited to 0.5 requests per second.',
  '',
  '1. Go to https://portal.jup.ag',
  '2. Create a free account and generate an API key',
  '3. Add it to your .env file',
  '',
  '### 5. Add your wallet private key',
  '',
  'Export your wallet private key as a JSON byte array or base58 string.',
  'Add it to .env as USER_PRIVATE_KEY.',
  '',
  '**Security**: This key stays on your machine. The bot only sends signed',
  'transactions to the Solana network.',
  '',
  '### 6. Start the bot',
  '',
  '```bash',
  'npm start',
  '```',
  '',
  '## Architecture',
  '',
  '- config.ts: Configuration constants (pair, amounts, thresholds)',
  '- utils.ts: Logging, retry logic, sleep, backoff utilities',
  '- monitor.ts: Polls Jupiter for quotes, identifies opportunities',
  '- math.ts: Profit calculation with fee deduction',
  '- executor.ts: Builds and sends transactions (WSOL wrapping, ALT dedup)',
  '- index.ts: Entry point, orchestrates the monitor-evaluate-execute loop',
  '',
  '## Troubleshooting',
  '',
  '**Rate limited**: Add a Jupiter API key to your .env file.',
  '**Transaction too large**: Reduce venue count or use a simpler pair.',
  '**Insufficient funds**: Deposit more SOL.',
  '**No opportunities found**: Expected. DEX prices are usually in equilibrium.',
  '',
  '## Disclaimer',
  '',
  'Trading involves risk of financial loss. This code is provided as-is with no',
  'guarantees of profitability. Always test with small amounts first.',
].join('\n') + '\n';

// ── Main Route ──

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const payload = validatePayload(body);

    const zip = new JSZip();

    zip.file('package.json', genPackageJson(payload));
    zip.file('tsconfig.json', TSCONFIG);
    zip.file('.env.example', ENV_EXAMPLE);
    zip.file('README.md', README_MD);
    
    zip.file('src/config.ts', genConfigTs(payload));
    zip.file('src/utils.ts', UTILS_TS);
    zip.file('src/monitor.ts', genMonitorTs(payload));
    zip.file('src/math.ts', genMathTs(payload));
    zip.file('src/executor.ts', genExecutorTs(payload));
    zip.file('src/index.ts', genIndexTs(payload));

    const zipBuffer = await zip.generateAsync({ type: 'arraybuffer', compression: 'DEFLATE', compressionOptions: { level: 9 } });

    return new Response(zipBuffer as unknown as BodyInit, {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': 'attachment; filename="arbitrator-bot.zip"',
        'X-Content-Type-Options': 'nosniff',
      },
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Internal Server Error';
    return new Response(msg, { status: 400, headers: { 'X-Content-Type-Options': 'nosniff' } });
  }
}
